import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header"; // <--- Import Header vừa tạo
import NextTopLoader from "nextjs-toploader";
import Footer from "@/components/home/Footer";
import QueryProvider from "@/components/providers/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vina Travel - Tours Booking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="relative z-10">
            <div className="min-h-screen bg-transparent">
              <NextTopLoader />
              <Header />
              {children}
              <Footer />
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
